name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate green snake
        uses: Platane/snk@v3
        with:
          # this always resolves correctly to your username
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.gif?color_snake=#2ecc71&color_dots=#f5f5f5,#dcdcdc,#a8e6a1,#5fd068,#2ecc71
            dist/github-contribution-grid-snake.svg?color_snake=#2ecc71&color_dots=#f5f5f5,#dcdcdc,#a8e6a1,#5fd068,#2ecc71

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
