name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate brown snake
        uses: Platane/snk@v3
        with:
          github_user_name: AksharaDebnath
          outputs: |
            dist/github-contribution-grid-snake.gif
        env:
          SNAKE_COLOR: "#895129"          # brown snake
          SNAKE_BACKGROUND: "#0b0f1a"     # dark background
          SNAKE_DOT_COLOR: "#2a2a2a"      # empty grid
          SNAKE_EATEN_DOT_COLOR: "#C19A6B" # light brown eaten squares

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
